### ISSUE TITLE
JOSS review: documentation

### ISSUE THREAD

**Issue by mefuller** [pybamm-team/liionpack#126]
I am unable to find a link to proper documentation, just example notebooks.
Where is the documentation to be found? Please make the location more visible on the main page

**Comment by priyanshuone6** [comment]
@mefuller thanks for catching that. The link to the documentation can be found in the [contributing guidelines](https://github.com/pybamm-team/liionpack/blob/main/docs/contributing.md). I'll make a PR and include it in the readme.

Documentation link - https://liionpack.readthedocs.io/

**Comment by mefuller** [comment]
Thanks - I still don't see a clear overview of commands, just examples.
The documentation would definitely need to include that to pass JOSS review

**Comment by TomTranter** [comment]
The docs can be found by clicking on the docs badge in the readme on the homepage. I can also include an explicit link

**Comment by TomTranter** [comment]
Overview of commands can be found here https://liionpack.readthedocs.io/en/main/reference/
