### ISSUE TITLE
[Bug]: The example code on the website cannot be run

### ISSUE THREAD

**Issue by canterville12** [pybamm-team/liionpack#164]
### liionpack Version

Most recent version, just after the "pip install liionpack" 

### Python Version

3.9.13

### Describe the bug

When opening the "01 Getting Started" page [here](https://liionpack.readthedocs.io/en/latest/examples/01%20Getting%20Started/), after following the instructions exactly, the code cannot run, it says: "AttributeError: param.C_n_init does not exist. It may have been renamed to param.n.C_init".

**Comment by tinosulzer** [comment]
Working on this

**Comment by tinosulzer** [comment]
Looks like this has been fixed in main but not yet released

**Comment by TomTranter** [comment]
Hi @canterville12 I just published a new release on pypi which hopefully should resolve your issue.

**Comment by TomTranter** [comment]
No response so assume fixed
