### ISSUE TITLE
Model not converging with P2D and modified P2D

### ISSUE THREAD

**Issue by neokzp** [pybamm-team/liionpack#166]
I tried using standard P2D models and modified version with MHC kinetics.

It seems the model cannot either find an initial condition or converging afterwards.

Is that supposed to behave like this as it's still on early stage and need more future work or I just doing something wrong?

**Comment by TomTranter** [comment]
Hi @neokzp thanks for the question but I'm going to need to see the code you are running to be able to help

**Comment by TomTranter** [comment]
Closing as no response from op
