### ISSUE TITLE
CONFIGURATION CONNECTION OF THE BATTERY PACK

### ISSUE THREAD

**Issue by SyarifulAzis1018** [pybamm-team/liionpack#167]
### Description

So far, the circuit connection in liionpack library use series then parallel connection. in the other side, we can setting the connection with the parallel first and then parallel

### Motivation

I read from some literature, this configuration more reliable for unbalance voltage of battery. so if liionpack can make more configuration of battery its so very nice.

### Possible Implementation

i think the implementation can simulate energy storage for power grid.

**Comment by TomTranter** [comment]
If you can generate a circuit diagram in LtSpice or something we can import netlist and then we can see how easy to auto generate. Thanks for the suggestion

**Comment by SyarifulAzis1018** [comment]
[https://drive.google.com/file/d/1e1DCaLWT3BzXe37hdTaYFMSm03JQk4_x/view?usp=sharing](url)
this file about the circuit 3p2s, thanks

**Comment by TomTranter** [comment]
Do you know if the convention is to call this configuration 3p2s and the way liionpack does it 2s3p? I think this should be easy to automate, just wondering about the best way to define the layout with terminology or maybe an argument like series_first = True

**Comment by SyarifulAzis1018** [comment]
I think it's goog choices to define the layout

**Comment by jiean520** [comment]
> I think it's good choices to define the layout

Do you have a good way to do it? I also face this problem now.
