### ISSUE TITLE
Runtime errro: pdflatex is not installed[Bug]: 

### ISSUE THREAD

**Issue by Jadhav-Sourabh** [pybamm-team/liionpack#172]
### liionpack Version

0.3.2

### Python Version

3.8

### Describe the bug

I tried simple code from documentation to check whether its working or not. then I got runtime error: pdflatex is not installed. I am using windows

**Comment by priyanshuone6** [comment]
Please refer [this](https://lcapy.readthedocs.io/en/latest/install.html) link on how to install pdflatex and required dependencies for windows.

**Comment by Sourabh-Jadhav-2** [comment]
> Please refer [this](https://lcapy.readthedocs.io/en/latest/install.html) link on how to install pdflatex and required dependencies for windows.

![MicrosoftTeams-image](https://user-images.githubusercontent.com/87997086/181171308-4e25f90a-f046-4e60-a4fe-dc5ae739d2f7.png)

**Comment by TomTranter** [comment]
You need tex. Please go through the above link carefully

**Comment by balaji3112** [comment]
I'm facing the same issue. I tried installing the required dependencies in the link but still got the same error.

  File "C:\Users\Welcome\AppData\Local\Programs\Python\Python38\lib\site-packages\lcapy\system.py", line 72, in checkexe
    raise RuntimeError('%s is not installed' % program)
RuntimeError: pdflatex is not installed

**Comment by TomTranter** [comment]
Make sure you have the filepath in your environment path

**Comment by balaji3112** [comment]
I added the pdflatex path to the environment variables, but the problem persists.

**Comment by TomTranter** [comment]
Try adding to the top of the list in the Path variable for both user and system. I had an issue the other day with this myself and it was fixed by moving up the list
