### ISSUE TITLE
Documentation link in sidebar

### ISSUE THREAD

**Issue by wigging** [pybamm-team/liionpack#181]
### Description

Please add a link to the documentation in the sidebar on GitHub.

### Motivation

Putting a link in the sidebar to the repo documentation is standard practice.

### Possible Implementation

Just add the documentation link in the Website field on the sidebar. The link will display in the About section.

**Comment by TomTranter** [comment]
Can you check if I've done what you meant

**Comment by wigging** [comment]
I see the link. Thanks.
![screenshot](https://user-images.githubusercontent.com/6828967/183126537-cd7ae9e9-1c53-4764-8beb-da109fdf00d6.png)
