### ISSUE TITLE
External variable and inputs getting mixed in causes input_parameter_order to fail[Bug]: 

### ISSUE THREAD

**Issue by TomTranter** [pybamm-team/liionpack#191]
### liionpack Version

develop

### Python Version

All

### Describe the bug

The latest fix to the inputs fails when there is an external variable

**Comment by tinosulzer** [comment]
Do you need help fixing? Is it a liionpack bug or pybamm?

**Comment by TomTranter** [comment]
It's liionpack - I think I've done it but it's more like a hack to the hack than a real solution.
