### ISSUE TITLE
[Bug]: key error 'electric'

### ISSUE THREAD

**Issue by SourabhJadhav2** [pybamm-team/liionpack#197]
### liionpack Version

0.3

### Python Version

3.8

### Describe the bug

`
   I, typ = op["electric"]
`
`
KeyError: 'electric'
`

### Steps to Reproduce

try to solve this example: https://liionpack.readthedocs.io/en/main/examples/08%20SEI%20degradation%20model/

**Comment by tinosulzer** [comment]
Duplicate of #195 , PR is open #196
