### ISSUE TITLE
[Bug]: KeyError: 'electric'

### ISSUE THREAD

**Issue by dirge1** [pybamm-team/liionpack#199]
### liionpack Version

0.3.2

### Python Version

3.7

### Describe the bug

Hello! 

This is my first time using this package. No matter what code I run, I get the following error.

I, typ = op["electric"]
KeyError: 'electric'

I found that someone had the same problem in "Issues" , but I didn't find a solution. Has this problem been solved? Thank you very much for your help!

**Comment by TomTranter** [comment]
Hi @dirge1, I am working on a fix for this at the moment. Turns out something else broke at the same time too so fixing both which is taking longer
