### ISSUE TITLE
[Bug]: TypeError: solve() got an unexpected keyword argument 'htc'

### ISSUE THREAD

**Issue by skywo1f** [pybamm-team/liionpack#200]
### liionpack Version

June 2022

### Python Version

3.8

### Describe the bug

Got this error when running the basic example from the readme:

`TypeError: solve() got an unexpected keyword argument 'htc'`

### Steps to Reproduce

follow steps to create environment, activate environment,
copy README code into test.py
run test.py

### Expected behaviour

run the basic example

### Relevant log output

```shell
~/batterySims/liionpack$ python3 testLiion.py 
Traceback (most recent call last):
  File "testLiion.py", line 30, in <module>
    output = lp.solve(netlist=netlist, parameter_values=parameter_values, experiment=experiment, output_variables=output_variables,htc=htc)
TypeError: solve() got an unexpected keyword argument 'htc'
```

### Additional context
 If I remove that htc line, then the simulation seems to run (for Mohtat2020, not Prada2013)
_No response_

**Comment by skywo1f** [comment]
working tests:
test_all_solvers.py
test_logger.py
test_netlist_utils.py
test_protocols.py
test_simulations.py
test_utils.py

not working tests:
test_1p1s.py
test_notebooks.py
test_plots.py
test_sim_utils.py
test_solvers.py
test_solver_utils.py

**Comment by skywo1f** [comment]
A lot of the errors involve:
`AttributeError: 'ElectrodeSOHSolver' object has no attribute 'get_initial_stoichiometries'`

**Comment by skywo1f** [comment]
setting the `initial_soc=0.5` parameter seems to be the cause of that attributeError

**Comment by TomTranter** [comment]
Hi @skywo1f thanks for raising this issue and others. I recently made this change and tested it against the pybamm dev branch. Can you try the same? I know this isn't a great situation but we haven't yet synced up our release process which we should revisit @tinosulzer

**Comment by tinosulzer** [comment]
We did not go into this as software experts and are kind of learning how to do things (and why things are done the way they are) as we go but this disclaimer explains how you should view pybamm releases
https://github.com/pybamm-team/PyBaMM#versioning

**Comment by skywo1f** [comment]
I am currently using Pybamm=22.11.1, and liionpack=0.3.2 and having those issues.

**Comment by TomTranter** [comment]
Hopefully this is fixed in the latest release

**Comment by TomTranter** [comment]
Closing as inactive
