### ISSUE TITLE
[Bug]:always high voltage limit 

### ISSUE THREAD

**Issue by jiean520** [pybamm-team/liionpack#228]
### liionpack Version

0.3.4

### Python Version

3.9

### Describe the bug

The newest version of liionpack 0.3.4 can not run any example code. Always reached high voltage limit. The same code can be run in the version of 0.3.3

**Comment by TomTranter** [comment]
Try upgrading pybamm too

**Comment by jiean520** [comment]
> Try upgrading pybamm too

Both liionpack(0.3.4) and pybamm(23.2) are newest. Still can not run.

**Comment by TomTranter** [comment]
Ok I had some issues with branches yesterday when I made the release but all tests were passing. I'll take a look ASAP

**Comment by TomTranter** [comment]
Right sorry about this. Can you roll back to previous version of liionpack for now. I have current version in step with the PyBaMM develop branch.

**Comment by TomTranter** [comment]
This should be fixed now in latest versions on pip
