### ISSUE TITLE
Liionpack uses the opposite sign convention from pybamm

### ISSUE THREAD

**Issue by valentinsulzer** [pybamm-team/liionpack#32]
In pybamm, discharge current is positive and charge current is negative.
In liionpack, it is the other way round. This might cause confusion. Can I just fix as part of #9?

**Comment by TomTranter** [comment]
Hmm, ok that's funny. Might be that the direction of the elements in the circuit graph need changing too

**Comment by wigging** [comment]
Most of the circuit code is in `netlist_utils.py`.
