### ISSUE TITLE
Possible optimization in `solve_circuit`

### ISSUE THREAD

**Issue by tinosulzer** [pybamm-team/liionpack#34]
If I understand correctly, `solve_circuit` constructs the `A` and `z` matrices each time it is called, then solves `Ax=z`. Doing some very basic profiling, around 85% of the time is spent setting up the `A` matrix and 15% solving the linear system (this is for the `load_netlist.py` example, I haven't tested how this scales with pack size). 

Does the `A` matrix change between iterations or is it always the same? If it always stays the same, constructing it once outside of `solve_circuit` would significantly speed up `solve_circuit`, at least for the circuit size I tried

**Comment by TomTranter** [comment]
address with #67
