### ISSUE TITLE
Run Black formatting when PRs are merged

### ISSUE THREAD

**Issue by TomTranter** [pybamm-team/liionpack#43]

**Comment by priyanshuone6** [comment]
https://github.com/psf/black/actions/runs/17913292/workflow

**Comment by Saransh-cpp** [comment]
If we don't want to use `tox` then `BattBot`'s workflow would work - 
https://github.com/pybamm-team/BattBot/blob/0d054b03422a6b117ec5491909a538af79e15cc1/.github/workflows/python-app.yml#L13-L26

**Comment by priyanshuone6** [comment]
@Saransh-cpp Are you working on this issue?
