### ISSUE TITLE
HELP readthedocs nightmare!

### ISSUE THREAD

**Issue by TomTranter** [pybamm-team/liionpack#47]
I have no idea why but it seems like readthedocs is stuck reading from an old commit. It won't update the additional pages. Seems to update index ok. I'm using MKDocs which is supposed to make life simple. If I start a server locally it all looks ok :(

**Comment by priyanshuone6** [comment]
@TomTranter maybe try [creating a webhook](https://docs.readthedocs.io/en/stable/webhooks.html) to automatically update the docs with every push in the repository.

**Comment by TomTranter** [comment]
I've no idea why but it seems fixed now. Latest and main are the same
