### ISSUE TITLE
Switch to object-oriented programming?

### ISSUE THREAD

**Issue by valentinsulzer** [pybamm-team/liionpack#49]
This would be slightly more "pythonic". e.g.
- A `Circuit` class to handle loading a netlist, drawing, and solving
- A `Solver` class
- A `PackSolution` class to store, plot, save the solution

Though of course, there is nothing wrong with function-oriented programming as the code is currently designed.

**Comment by wigging** [comment]
I avoid writing classes as much as possible. Here is a classic Python presentation about using classes. https://youtu.be/o9pEzgHorH0
