### ISSUE TITLE
pack voltage bug

### ISSUE THREAD

**Issue by TomTranter** [pybamm-team/liionpack#56]
![image](https://user-images.githubusercontent.com/7068741/140034738-40dd2c29-4bfa-4723-9eb6-9cecd683e954.png)

**Comment by TomTranter** [comment]
I think this is also reversing the effect of the busbar resistance on the pack voltage

**Comment by wigging** [comment]
Can elaborate on what's going on here? Is the circuit diagram drawn wrong?
