### ISSUE TITLE
Documenting multiple return values

### ISSUE THREAD

**Issue by Saransh-cpp** [pybamm-team/liionpack#81]
Right now `mkdocstrings` doesn't support multiple return values or adding a name for the return values (hence the weird return values part in functions with > 1 return value).

![image](https://user-images.githubusercontent.com/74055102/142769121-31ba3230-4e21-4f62-b474-664fd40a0b51.png)

This can be worked upon once the feature is added in.

Refer - https://github.com/mkdocstrings/mkdocstrings/issues/301

**Comment by TomTranter** [comment]
@Saransh-cpp shall we close?
