### ISSUE TITLE
Include circuits, data, init_funcs in setup.py

### ISSUE THREAD

**Issue by priyanshuone6** [pybamm-team/liionpack#85]
## Describe the bug
Installing liionpack using `pip install -q git+https://github.com/pybamm-team/liionpack.git@main` does not include circuits, data, init_funcs folders in the package

<img width="802" alt="Screenshot 2021-11-23 083844" src="https://user-images.githubusercontent.com/64051212/142965835-1bf5d546-7cf6-4051-9466-4a63f504cc4d.png">

<img width="796" alt="Screenshot 2021-11-23 084018" src="https://user-images.githubusercontent.com/64051212/142965941-ab32c7ab-3fba-4a70-8888-c77e0f217f69.png">

## To Reproduce
Steps to reproduce the behaviour:
Run `02 Simulating a bespoke pack using an LTSpice netlist and custom heat transfer.ipynb` from examples/notebooks

## TO DO
Include these folders in setup.py

For Reference:
https://github.com/pybamm-team/PyBaMM/blob/5fbfec8a46945e99106cc166c283201513066425/setup.py#L136-L160

**Comment by priyanshuone6** [comment]
@TomTranter @wigging what files and extensions from these folders should I include in the package?

**Comment by TomTranter** [comment]
We might want to move all of these to a features folder. I'm not sure what to do with init_funcs as it was used for setting intial SoC which we changed how to do but actually for a pack problem where you might want to intialize with a bunch of different values it could be useful. The other two are quite bespoke and used for an example of loading in your own netlist. For now include everything
